### ISSUE TITLE
Composer error…

### ISSUE THREAD

**Issue by spiffin** [PhileCMS/Textile-Parser-Plugin#1]
"The requested package phile/textile could not be found in any version, there may be a typo in the package name."

?

**Comment by james2doyle** [comment]
I managed to install by using `dev-master` as the version requirement.

> Please provide a version constraint for the phile/textile requirement: **dev-master**

**Comment by spiffin** [comment]
Thanks, but now a dependency error:

php ~/bin/composer.phar require phile/textile
Please provide a version constraint for the phile/textile requirement: dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phile/textile dev-master -> satisfiable by phile/textile[dev-master].
    - phile/textile dev-master requires phile-cms/phile 1.0.0 -> no matching package found.

**Comment by james2doyle** [comment]
Which version of PhileCMS are you using?

**Comment by james2doyle** [comment]
It should say in your root `composer.json` file

https://github.com/PhileCMS/Phile/blob/master/composer.json#L3

**Comment by spiffin** [comment]
.. the most recent: 0.9.2

**Comment by james2doyle** [comment]
Sorry, but that isn't the most recent. It is [1.0.0](https://github.com/PhileCMS/Phile/tree/release/1.0.0) the current version of this plugin only works with 1.0.0.

You can still use this plugin with 0.9.2 but you need to use an old release

https://github.com/PhileCMS/Textile-Parser-Plugin/releases/tag/0.9

We are in the process of improving Phile in 1.0.0 which includes the composer installing of plugins and such. 

The old version 0.9.2 just used the download and extract method. It will include the readme in the download so use that to complete the installation.

**Comment by spiffin** [comment]
Okay, thanks. If you install via Composer (as I did) with:

php /path/to/composer.phar create-project phile-cms/phile

.. it installs 0.9.2. Maybe point that to version 1.0.0?

**Comment by james2doyle** [comment]
It isn't quite finished just yet, hopeful next week we can get it released.

You can check out the [PhileCMS Google Community](https://plus.google.com/communities/105363272048954062353) to keep up-to-date.

**Comment by spiffin** [comment]
I will, thanks.
